#!/usr/bin/env node
// Build pipeline: concatenates core/*.js into illustrator/lib/core.generated.jsx
// and validates all configs/journals/*.json against configs/schema.json.

"use strict";

const fs = require("fs");
const path = require("path");
const vm = require("vm");

const ROOT = path.resolve(__dirname, "..");
const CORE_DIR = path.join(ROOT, "core");
const OUT_FILE = path.join(ROOT, "illustrator", "lib", "core.generated.jsx");
const SCHEMA_FILE = path.join(ROOT, "configs", "schema.json");
const JOURNALS_DIR = path.join(ROOT, "configs", "journals");

// ── 1. Concatenate core modules ───────────────────────────────────────────────

const CORE_ORDER = ["bounds.js", "sizeRules.js", "fontRules.js", "scaleRules.js", "config.js"];

let output = "// AUTO-GENERATED by scripts/build.js — do not edit by hand.\n";
output += "// Source: core/*.js\n\n";

for (const file of CORE_ORDER) {
    const src = path.join(CORE_DIR, file);
    if (!fs.existsSync(src)) {
        console.error(`ERROR: Missing core file: ${src}`);
        process.exit(1);
    }
    let content = fs.readFileSync(src, "utf8");

    // Strip the Node module.exports guard — not valid in ExtendScript.
    // Use greedy [\s\S]* so the match extends to the *outer* closing brace
    // of the if-block, not the first } inside the object literal.
    content = content.replace(
        /\n?if\s*\(typeof\s+module\s*!==\s*["']undefined["']\)\s*\{[\s\S]*\}\s*\n?/g,
        "\n"
    );
    // Strip trailing whitespace lines
    content = content.trimEnd() + "\n";

    output += `// ── ${file} ────────────────────────────────────────────────────\n`;
    output += content + "\n";
}

fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
fs.writeFileSync(OUT_FILE, output, "utf8");
console.log(`Built: ${path.relative(ROOT, OUT_FILE)}`);

// ── 2. Syntax-check the generated file ───────────────────────────────────────
// vm.Script parses the source without executing it, catching brace mismatches
// and unexpected tokens before Illustrator ever sees the file.
try {
    new vm.Script(output, { filename: path.relative(ROOT, OUT_FILE) });
    console.log(`Syntax: ${path.relative(ROOT, OUT_FILE)} OK`);
} catch (err) {
    console.error(`Syntax error in generated file:\n${err.message}`);
    fs.unlinkSync(OUT_FILE); // remove the broken file so it isn't accidentally used
    process.exit(1);
}

// ── 3. Validate journal configs against schema ────────────────────────────────

let Ajv;
try {
    Ajv = require("ajv");
} catch (e) {
    console.warn("Warning: ajv not installed — skipping schema validation. Run: npm install");
    process.exit(0);
}

const AjvClass = Ajv.default || Ajv;
const ajv = new AjvClass({ allErrors: true });
const schema = JSON.parse(fs.readFileSync(SCHEMA_FILE, "utf8"));
const validate = ajv.compile(schema);

let allValid = true;
const journals = fs.readdirSync(JOURNALS_DIR).filter(f => f.endsWith(".json"));

for (const file of journals) {
    const filePath = path.join(JOURNALS_DIR, file);
    const config = JSON.parse(fs.readFileSync(filePath, "utf8"));
    const valid = validate(config);
    if (!valid) {
        console.error(`Schema error in configs/journals/${file}:`);
        for (const err of validate.errors) {
            console.error(`  ${err.instancePath || "/"} ${err.message}`);
        }
        allValid = false;
    } else {
        console.log(`Valid:  configs/journals/${file}`);
    }
}

if (!allValid) {
    console.error("Build failed: fix schema errors above.");
    process.exit(1);
}

console.log("Build complete.");
